In [1]:
#conect to the drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#import independacies
import numpy as np
import pandas as pd
import numpy as np

import ast

In [3]:
#import the data
data = pd.read_csv("/content/drive/MyDrive/bigdata_exc3/dtw_test.csv")

The DTWDistance function calculates the dynamic time warping (DTW) distance between two arrays s and t. Here's what the code does step by step:

1.  Initialize variables: The first two lines of the function extract the number of rows (i.e. the length) of the input arrays s and t, and assign the values to variables n and m. Then, a two-dimensional array DTW of size (n+1, m+1) is created, filled with the value np.inf (i.e. positive infinity).

2.  Set the starting point: The value at the first cell of the DTW array, DTW[0, 0], is set to 0. This represents the starting point of the DTW calculation.

3. Loop through arrays: The next two nested for-loops are used to iterate through the arrays s and t. The outer loop i goes from 1 to n+1 (inclusive), and the inner loop j goes from 1 to m+1 (inclusive).

4.  Calculate cost: At each iteration of the inner loop, the cost variable is calculated as the Euclidean distance between the current elements of s and t, i.e. np.linalg.norm(s[i-1]-t[j-1]). This represents the cost of matching the two elements.

5.  Update DTW array: The value of DTW[i, j] is then updated as the minimum of the values at the three cells above it: DTW[i-1, j], DTW[i, j-1], and DTW[i-1, j-1], plus the cost calculated in step 4. This implements the core dynamic programming step of DTW.

6.  Return result: Finally, the function returns the value at the last cell of the DTW array, DTW[n, m], which represents the DTW distance between the two input arrays.

In [4]:
def DTWDistance(s, t):
    n, m = s.shape[0], t.shape[0]
    DTW = np.full((n+1, m+1), np.inf)
    DTW[0, 0] = 0
    
    for i in range(1, n+1):
        for j in range(1, m+1):
            cost = np.linalg.norm(s[i-1]-t[j-1])
            DTW[i, j] = cost + min(DTW[i-1, j], 
                                    DTW[i, j-1],
                                    DTW[i-1, j-1])
    return DTW[n, m]

In [5]:
output = []

In [ ]:
import timeit
start_br_cos = timeit.default_timer()

for i in range(len(data)):
  #########series_a#########
  series_a = data.iloc[i,1]
  #convert from str to list
  series_a = ast.literal_eval(series_a)
  series_a = [float(i) for i in series_a]
  #convert form list to array in order the function bellow to work
  series_a = np.array(series_a)

  #########series_b#########
  series_b = data.iloc[i,2]
  #convert from str to list
  series_b = ast.literal_eval(series_b)
  series_b = [float(i) for i in series_b]
  #convert form list to array in order the function bellow to work
  series_b = np.array(series_b)

  output.append(DTWDistance(series_a,series_b))

end_br_cos = timeit.default_timer()
br_cos = end_br_cos-start_br_cos

In [ ]:
print(br_cos/60)

81.76588967526666

In [ ]:
output = pd.DataFrame (output, columns = ['distance'])

In [ ]:
output["Id"] = output.index

In [ ]:
output.head()

   distance  Id
0   18.8752   0
1   16.4397   1
2   12.0723   2
3   17.0150   3
4    8.7369   4

In [ ]:
DTW = output[['Id', 'distance']]

In [ ]:
DTW.head()

   Id  distance
0   0   18.8752
1   1   16.4397
2   2   12.0723
3   3   17.0150
4   4    8.7369

In [ ]:
DTW.to_csv("dtw.csv", index=False)